pipeline:
  identifier: Build_nktwn_Forum_N_1717779929975
  name: Build Forum_N
  orgIdentifier: default
  projectIdentifier: Forum
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: nktwn/Forum_N
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    repo: forum
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
